### ISSUE TITLE
Hello, could you help me? throws me this error: MulterSharpResizer error filename Param.split is not a function

### ISSUE THREAD

**Issue by Alejo-tech** [mohammadoftadeh/multer-sharp-resizer#1]
const multer = require('multer');
const path = require('path');
const MulterSharpResizer = require('multer-sharp-resizer');

/*const multerStorage = multer.memoryStorage();
const multerFilter = (req, file, cb) => {
    if (file.mimetype.startsWith("image")) {
        cb(null, true)
    } else {
        cb(null, false)
    }
}*/
const storageArticulos = multer.diskStorage({
    destination: function (request, file, callback) {
        console.log("REQ : " + request);
        callback(null, path.join(__filename, '../../../public/images/articulos'));
    },
    filename: function (req, file, cb) {
        cb(null, file.originalname);
    }
})

exports.uploadArticulos = multer({
    storage: storageArticulos
});

/*
exports.uploadArticulosImagenes = uploadArticulos.single('image');
exports.resizerUploadArticulos = async (req, res, next) => {
    const filename = {
        image: `image-${Date.now()}`
    };
    const sizes = [
        {
            path: "original",
            width: null,
            height: null,
        },
        {
            path: "large",
            width: 800,
            height: 800,
        },
        {
            path: "medium",
            width: 300,
            height: 300,
        },
        {
            path: "thumbnail",
            width: 100,
            height: 100,
        },
    ];

    const uploadPath = path.join(__filename, '../../../public/images/articulos');
    const fileUrl = `${req.protocol}://${req.get("host")}/images/articulos`;
    const sharpOptions = {
        fit: "image",
        background: { r: 255, g: 255, b: 255 }
    };

    const resizeObj = new MulterSharpResizer(
        req,
        filename,
        sizes,
        uploadPath,
        fileUrl,
        sharpOptions
    )
    await resizeObj.resize();
    const getDataUploaded = resizeObj.getData();
    console.log(getDataUploaded);
    next();

}
*/

**Comment by Alejo-tech** [comment]
That's my code
I'm trying to do it with upload.single ('image'), image is the name of the input that sends the data

**Comment by mohammadoftadeh** [comment]
Hi, Please note the code snippet below, as well as the example inside the README.md.

```javascript
// Used by multer .array() or .single
  // const filename = `gallery-${Date.now()}`;

  // Used by multer .fields and filename must be same object prop
  const filename = {
    cover: `cover-${Date.now()}`,
    gallery: `gallery-${Date.now()}`,
  };
```
