### ISSUE TITLE
error while install

### ISSUE THREAD

**Issue by mariam-montaser** [mohammadoftadeh/multer-sharp-resizer#2]
I cloned the repo but when installing it gives error 
npm ERR! code 1
npm ERR! info sharp Using cached
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@7.1.2
npm ERR! gyp info using node@16.9.1 | win32 | x64
 You need to install the latest version of Visual Studio
npm ERR! gyp ERR! find VS including the "Desktop development with C++" workload.
npm ERR! gyp ERR! find VS For more information consult the documentation at:
npm ERR! gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows

**Comment by mohammadoftadeh** [comment]
Hi Mariam, first update your node to LTS version, when installing `npm install` into CMD you can check with vpn.  Also check visual studio software and dependencies versions. The multer-sharp-resizer package works properly.
