### ISSUE TITLE
images are not loading from node js static folder in the browser

### ISSUE THREAD

**Issue by rggaaya3** [mohammadoftadeh/multer-sharp-resizer#4]
Hi , i am facing an issue, for me everything is working perfectly, but when hit the url in my browser , i mean the image path, its not working. the image is not loading. (http://localhost:3000/uploads/2022/10/original/cover=1665097696275-0-original.png)
I m getting this error "Cannot GET /uploads/2022/10/original/cover=1665097696275-0-original.png"

**Comment by rggaaya3** [comment]
Hi , I have fixed the issue myself. hence closing this issue. 
thanks for the video again :)

**Comment by mohammadoftadeh** [comment]
> 

Hi, I'm so glad the problems are fixed.
You're welcome ✌.
