### ISSUE TITLE
how to get original height and width of image

### ISSUE THREAD

**Issue by Sowmiya-Pachiappan** [mohammadoftadeh/multer-sharp-resizer#5]
I need original height and width of image to calculate aspect ratio of image . How to get it from multer-sharp-resizer?. Please help me.

**Comment by mohammadoftadeh** [comment]
If you carefully check the end of the documentation, Sizing structure. You can see:

> If `set` **`width: null`** and **`height: null`** , **The original size is saved by default**

**Comment by Sowmiya-Pachiappan** [comment]
Yes. But I want to store in variable. So is there any way to achieve that?

**Comment by mohammadoftadeh** [comment]
There are two ways:
1. You can calculate dimensions before upload and send dimentions like meta data with javascript, [Guide](https://stackoverflow.com/questions/5633264/javascript-get-image-dimensions) 
2. You can use [image-size](https://www.npmjs.com/package/image-size)  npm package

**Comment by Sowmiya-Pachiappan** [comment]
Thanks, I'll check it out.
